name:                lapse
version:             0.1.0.0
github:              "isovector/lapse"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isovector/lapse#readme>

dependencies:
- base >= 4.7 && < 5
# - gloss
# - gloss-export
# - gloss-juicy
# - htdp-image
- process
- temporary
- time
- async
- directory
- diagrams
- diagrams-core
- diagrams-lib
- diagrams-rasterific

library:
  source-dirs: src

executables:
  lapse-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lapse

tests:
  lapse-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lapse
